# Auto-generated Python type stubs for RSCM components
# This file is generated by rscm-doc-gen - do not edit manually

from typing import TypedDict

from rscm._lib.core import ComponentBuilder, RustComponent

class OceanSurfacePartialPressureParams(TypedDict):
    """Calculate partial pressure of |CO2| at the ocean's surface"""

    # Pre-industrial ocean surface partial pressure - unit: `ppm`
    ospp_preindustrial: float
    # Sensitivity of the ocean surface's partial pressure to changes in sea - unit: `1
    sensitivity_ospp_to_temperature: float
    # Pre-industrial sea surface temperature - unit: `degC`
    sea_surface_temperature_preindustrial: float
    # Vector of length 5 of offsets to be used when calculating the change in - unit:
    delta_ospp_offsets: list[float]
    # Vector of length 5 of coefficients (applied to pre-industrial sea surface temper
    delta_ospp_coefficients: list[float]

class OceanSurfacePartialPressureBuilder(ComponentBuilder):
    """Calculate partial pressure of |CO2| at the ocean's surface"""

    @staticmethod
    def from_parameters(
        parameters: OceanSurfacePartialPressureParams,
    ) -> OceanSurfacePartialPressureBuilder:
        """Create a builder from a parameter dictionary."""
        ...
    def build(self) -> RustComponent:
        """Build the component."""
        ...
