# Auto-generated Python type stubs for RSCM components
# This file is generated by rscm-doc-gen - do not edit manually

from typing import TypedDict

from rscm._lib.core import ComponentBuilder, RustComponent

class FourBoxOceanHeatUptakeParams(TypedDict):
    """Four-box ocean heat uptake component"""

    # Ratio of Northern Ocean uptake to global ERF (regional / global)
    northern_ocean_ratio: float
    # Ratio of Northern Land uptake to global ERF (regional / global)
    northern_land_ratio: float
    # Ratio of Southern Ocean uptake to global ERF (regional / global)
    southern_ocean_ratio: float
    # Ratio of Southern Land uptake to global ERF (regional / global)
    southern_land_ratio: float

class FourBoxOceanHeatUptakeBuilder(ComponentBuilder):
    """Four-box ocean heat uptake component"""

    @classmethod
    def from_parameters(
        cls, parameters: FourBoxOceanHeatUptakeParams
    ) -> FourBoxOceanHeatUptakeBuilder:
        """Create a builder from a parameter dictionary."""
        ...
    def build(self) -> RustComponent:
        """Build the component."""
        ...

class CarbonCycleParams(TypedDict):
    """Carbon cycle component"""

    # Timescale of the box's response - unit: yr
    tau: float
    # Pre-industrial atmospheric CO2 concentration - unit: ppm
    conc_pi: float
    # Sensitivity of lifetime to changes in global-mean temperature - unit: 1 / K
    alpha_temperature: float

class CarbonCycleBuilder(ComponentBuilder):
    """Carbon cycle component"""

    @classmethod
    def from_parameters(cls, parameters: CarbonCycleParams) -> CarbonCycleBuilder:
        """Create a builder from a parameter dictionary."""
        ...
    def build(self) -> RustComponent:
        """Build the component."""
        ...

class CO2ERFParams(TypedDict):
    """CO2 Effective Radiative Forcing component"""

    # ERF due to a doubling of atmospheric CO2 concentrations - unit: W / m^2
    erf_2xco2: float
    # Pre-industrial atmospheric CO2 concentration - unit: ppm
    conc_pi: float

class CO2ERFBuilder(ComponentBuilder):
    """CO2 Effective Radiative Forcing component"""

    @classmethod
    def from_parameters(cls, parameters: CO2ERFParams) -> CO2ERFBuilder:
        """Create a builder from a parameter dictionary."""
        ...
    def build(self) -> RustComponent:
        """Build the component."""
        ...
