# Auto-generated Python type stubs for RSCM components
# This file is generated by rscm-doc-gen - do not edit manually

from typing import TypedDict

from rscm._lib.core import ComponentBuilder, RustComponent

class TwoLayerParams(TypedDict):
    """Two-layer energy balance model component implementation."""

    # Climate feedback parameter at zero warming - unit: W/(m² K)
    lambda0: float
    # Nonlinear feedback coefficient - unit: W/(m² K²)
    a: float
    # Ocean heat uptake efficacy - unit: dimensionless
    efficacy: float
    # Heat exchange coefficient between surface and deep layers - unit: W/(m² K)
    eta: float
    # Heat capacity of the surface layer (mixed layer ocean + atmosphere) - unit: W yr
    heat_capacity_surface: float
    # Heat capacity of the deep ocean layer - unit: W yr/(m² K)
    heat_capacity_deep: float

class TwoLayerBuilder(ComponentBuilder):
    """Two-layer energy balance model component implementation."""

    @classmethod
    def from_parameters(cls, parameters: TwoLayerParams) -> TwoLayerBuilder:
        """Create a builder from a parameter dictionary."""
        ...
    def build(self) -> RustComponent:
        """Build the component."""
        ...
