//! JSON schema types for component metadata
//!
//! These types define the structure of the JSON files generated by rscm-doc-gen.

use serde::{Deserialize, Serialize};

/// Metadata for a single variable (input, output, or state)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VariableMetadata {
    /// Rust field name (e.g., "emissions_co2")
    pub rust_name: String,
    /// Variable name in the model (e.g., "Atmospheric Concentration|CO2")
    pub variable_name: String,
    /// Physical units (e.g., "ppm")
    pub unit: String,
    /// Spatial grid type (Scalar, FourBox, Hemispheric)
    pub grid: String,
    /// Description from doc comments
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub description: String,
}

/// Metadata for a component parameter
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParameterMetadata {
    /// Parameter name
    pub name: String,
    /// Rust type (e.g., "f64", "SolverOptions")
    #[serde(rename = "type")]
    pub param_type: String,
    /// Physical units (if documented)
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub unit: String,
    /// Description from doc comments
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub description: String,
    /// Default value (if any)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<String>,
}

/// Complete metadata for a component
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComponentDocMetadata {
    /// JSON schema reference
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Component struct name (e.g., "CarbonCycleComponent")
    pub name: String,
    /// Full module path (e.g., "rscm_components::components::carbon_cycle")
    pub module_path: String,
    /// Implementation language
    pub language: String,
    /// Component description extracted from doc comments
    pub description: String,
    /// LaTeX equations extracted from doc comments (between $$ markers)
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub equations: String,
    /// Primary category for grouping
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Tags for filtering
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    /// Input variable definitions
    pub inputs: Vec<VariableMetadata>,
    /// Output variable definitions
    pub outputs: Vec<VariableMetadata>,
    /// State variable definitions
    pub states: Vec<VariableMetadata>,
    /// Component parameters
    pub parameters: Vec<ParameterMetadata>,
    /// Python builder class (if applicable)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub python_builder: Option<String>,
    /// Source file path relative to workspace root
    pub source_file: String,
    /// Related documentation files
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub related_docs: Vec<String>,
}

impl Default for ComponentDocMetadata {
    fn default() -> Self {
        Self {
            schema: Some("component_metadata_schema.json".to_string()),
            name: String::new(),
            module_path: String::new(),
            language: "rust".to_string(),
            description: String::new(),
            equations: String::new(),
            category: None,
            tags: Vec::new(),
            inputs: Vec::new(),
            outputs: Vec::new(),
            states: Vec::new(),
            parameters: Vec::new(),
            python_builder: None,
            source_file: String::new(),
            related_docs: Vec::new(),
        }
    }
}
