import numpy as np
from numpy.typing import NDArray

# RSCM uses 64bit floats throughout
Arr = NDArray[np.float64]
F = np.float64 | float

# StateValue represents values that can be scalar or spatially-resolved.
# In the Rust core, this is an enum with three variants:
#   - Scalar(float): A single global value
#   - FourBox(FourBoxSlice): Four-box regional values
#   - Hemispheric(HemisphericSlice): Hemispheric values
#
# Note: In the Python API, component solve() currently returns scalars
# (aggregated via to_scalar()). This type alias documents the underlying
# type system for components that may work with grid values directly.
StateValue = float | "FourBoxSlice" | "HemisphericSlice"

class FourBoxSlice:
    @property
    def northern_ocean(self) -> float: ...
    @northern_ocean.setter
    def northern_ocean(self, value: float) -> None: ...
    @property
    def northern_land(self) -> float: ...
    @northern_land.setter
    def northern_land(self, value: float) -> None: ...
    @property
    def southern_ocean(self) -> float: ...
    @southern_ocean.setter
    def southern_ocean(self, value: float) -> None: ...
    @property
    def southern_land(self) -> float: ...
    @southern_land.setter
    def southern_land(self, value: float) -> None: ...
    def __init__(
        self,
        northern_ocean: float = ...,
        northern_land: float = ...,
        southern_ocean: float = ...,
        southern_land: float = ...,
    ) -> None: ...
    @staticmethod
    def uniform(value: float) -> FourBoxSlice: ...
    @staticmethod
    def from_array(values: list[float]) -> FourBoxSlice: ...
    def get(self, region: int) -> float: ...
    def set(self, region: int, value: float) -> None: ...
    def to_array(self) -> Arr: ...
    def to_list(self) -> list[float]: ...
    def to_dict(self) -> dict[str, float]: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class HemisphericSlice:
    northern: float
    southern: float

    def __init__(
        self,
        northern: float = ...,
        southern: float = ...,
    ) -> None: ...
    @staticmethod
    def uniform(value: float) -> HemisphericSlice: ...
    @staticmethod
    def from_array(values: list[float]) -> HemisphericSlice: ...
    def get(self, region: int) -> float: ...
    def set(self, region: int, value: float) -> None: ...
    def to_array(self) -> Arr: ...
    def to_list(self) -> list[float]: ...
    def to_dict(self) -> dict[str, float]: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class TimeseriesWindow:
    """Zero-cost view into scalar timeseries data."""

    current_index: int

    def __init__(self, values: list[float], current_index: int) -> None: ...
    @property
    def current(self) -> float: ...
    @property
    def previous(self) -> float: ...
    def at_offset(self, offset: int) -> float: ...
    def last_n(self, n: int) -> Arr: ...
    def to_array(self) -> Arr: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class FourBoxTimeseriesWindow:
    """View into FourBox grid timeseries data."""

    current_index: int

    def __init__(self, values: list[list[float]], current_index: int) -> None: ...
    @property
    def current(self) -> FourBoxSlice: ...
    @property
    def previous(self) -> FourBoxSlice: ...
    def region(self, region: int) -> TimeseriesWindow: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class HemisphericTimeseriesWindow:
    """View into Hemispheric grid timeseries data."""

    current_index: int

    def __init__(self, values: list[list[float]], current_index: int) -> None: ...
    @property
    def current(self) -> HemisphericSlice: ...
    @property
    def previous(self) -> HemisphericSlice: ...
    def region(self, region: int) -> TimeseriesWindow: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
