import numpy as np
from numpy.typing import NDArray

# RSCM uses 64bit floats throughout
Arr = NDArray[np.float64]
F = np.float64 | float

class FourBoxSlice:
    northern_ocean: float
    northern_land: float
    southern_ocean: float
    southern_land: float

    def __init__(
        self,
        northern_ocean: float = ...,
        northern_land: float = ...,
        southern_ocean: float = ...,
        southern_land: float = ...,
    ) -> None: ...
    @staticmethod
    def uniform(value: float) -> FourBoxSlice: ...
    @staticmethod
    def from_array(values: list[float]) -> FourBoxSlice: ...
    def get(self, region: int) -> float: ...
    def set(self, region: int, value: float) -> None: ...
    def to_array(self) -> Arr: ...
    def to_list(self) -> list[float]: ...
    def to_dict(self) -> dict[str, float]: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __len__(self) -> int: ...

class HemisphericSlice:
    northern: float
    southern: float

    def __init__(
        self,
        northern: float = ...,
        southern: float = ...,
    ) -> None: ...
    @staticmethod
    def uniform(value: float) -> HemisphericSlice: ...
    @staticmethod
    def from_array(values: list[float]) -> HemisphericSlice: ...
    def get(self, region: int) -> float: ...
    def set(self, region: int, value: float) -> None: ...
    def to_array(self) -> Arr: ...
    def to_list(self) -> list[float]: ...
    def to_dict(self) -> dict[str, float]: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __len__(self) -> int: ...

class TimeseriesWindow:
    """Zero-cost view into scalar timeseries data."""

    current_index: int

    def __init__(self, values: list[float], current_index: int) -> None: ...
    @property
    def current(self) -> float: ...
    @property
    def previous(self) -> float: ...
    def at_offset(self, offset: int) -> float: ...
    def last_n(self, n: int) -> Arr: ...
    def to_array(self) -> Arr: ...
    def __len__(self) -> int: ...

class FourBoxTimeseriesWindow:
    """View into FourBox grid timeseries data."""

    current_index: int

    def __init__(self, values: list[list[float]], current_index: int) -> None: ...
    @property
    def current(self) -> FourBoxSlice: ...
    @property
    def previous(self) -> FourBoxSlice: ...
    def region(self, region: int) -> TimeseriesWindow: ...
    def __len__(self) -> int: ...

class HemisphericTimeseriesWindow:
    """View into Hemispheric grid timeseries data."""

    current_index: int

    def __init__(self, values: list[list[float]], current_index: int) -> None: ...
    @property
    def current(self) -> HemisphericSlice: ...
    @property
    def previous(self) -> HemisphericSlice: ...
    def region(self, region: int) -> TimeseriesWindow: ...
    def __len__(self) -> int: ...
