name: "Setup Python and uv"
description: "setup Python and uv with caches"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.20"
        enable-cache: true
    # Install dependencies and builds the rust crate
    - name: Install the project
      shell: bash
      run: |
        uv sync --all-extras --dev --locked
      env:
        RUST_BACKTRACE: 1
