"""
MAGICC regression tests.

Validates RSCM MAGICC implementation against reference outputs
from Fortran MAGICC7. Tests are progressively unskipped as
components are implemented.

Reference data generated by:
  scripts/generate_magicc_regression_data.py

Test scenarios:
  01: Concentration-driven with IPCCTAR forcing method
  02: GHG forcing with OLBL method (modern AR6 approach)
  03: Emissions-driven with full carbon cycle
  04: Climate sensitivity sweep (ECS 1.5-4.5K, parametrised)
  05: CO2-only forcing mode
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import numpy.testing as npt
import pandas as pd
import pytest

from rscm._lib.core import (
    GridType,
    InterpolationStrategy,
    TimeAxis,
    Timeseries,
    VariableSchema,
)
from rscm._lib.magicc import (
    AerosolDirectBuilder,
    AerosolIndirectBuilder,
    CH4ChemistryBuilder,
    ClimateUDEBBuilder,
    CO2BudgetBuilder,
    GhgForcingBuilder,
    N2OChemistryBuilder,
    OceanCarbonBuilder,
    OzoneForcingBuilder,
    TerrestrialCarbonBuilder,
)
from rscm.core import ModelBuilder

# Reference data location (relative to this file)
REGRESSION_DATA_DIR = Path(__file__).parent / "regression_data" / "magicc"

# Default tolerances for numerical comparisons
DEFAULT_RTOL = 1e-3  # 0.1% relative tolerance
DEFAULT_ATOL = 1e-6  # Absolute tolerance for near-zero values


def load_regression_data(name: str) -> tuple[pd.DataFrame, dict]:
    """
    Load regression test data and config.

    Parameters
    ----------
    name
        Test name (e.g., "01_concentration_driven")

    Returns
    -------
    tuple[pd.DataFrame, dict]
        Long-format DataFrame and config dictionary

    Raises
    ------
    pytest.skip
        If reference data files are not found
    """
    parquet_path = REGRESSION_DATA_DIR / f"{name}.parquet"
    config_path = REGRESSION_DATA_DIR / f"{name}_config.json"

    if not parquet_path.exists():
        pytest.skip(f"Reference data not found: {parquet_path}")

    df = pd.read_parquet(parquet_path)

    # Validate expected columns exist
    expected_cols = {"year", "variable", "unit", "region", "value"}
    actual_cols = set(df.columns)
    if not expected_cols.issubset(actual_cols):
        missing = expected_cols - actual_cols
        msg = f"Parquet file missing columns: {missing}"
        raise ValueError(msg)

    config = {}
    if config_path.exists():
        with open(config_path) as f:
            config = json.load(f)

    return df, config


def get_variable_values(
    df: pd.DataFrame,
    variable: str,
    region: str = "World",
) -> tuple[np.ndarray, np.ndarray]:
    """
    Extract values for a variable as numpy arrays.

    Parameters
    ----------
    df
        Long-format DataFrame from load_regression_data
    variable
        Variable name (MAGICC naming convention)
    region
        Region to filter by (default "World")

    Returns
    -------
    tuple[np.ndarray, np.ndarray]
        (years, values) arrays sorted by year
    """
    subset = df[(df["variable"] == variable) & (df["region"] == region)]
    subset = subset.sort_values("year")

    if len(subset) == 0:
        msg = f"Variable '{variable}' not found for region '{region}'"
        raise ValueError(msg)

    return subset["year"].values, subset["value"].values


def magicc_to_rscm_variable(magicc_var: str) -> str:
    """
    Convert MAGICC variable name to RSCM convention.

    MAGICC uses plural "Concentrations", RSCM uses singular "Concentration".
    """
    return magicc_var.replace("Concentrations", "Concentration")


def rscm_to_magicc_variable(rscm_var: str) -> str:
    """
    Convert RSCM variable name to MAGICC convention (for looking up reference data).
    """
    return rscm_var.replace("Concentration|", "Concentrations|")


def build_ghg_forcing_model(
    years: np.ndarray,
    co2_conc: np.ndarray,
    ch4_conc: np.ndarray,
    n2o_conc: np.ndarray,
    config: dict,
):
    """
    Build a model with GhgForcing component for concentration-driven runs.

    Parameters
    ----------
    years
        Array of year values
    co2_conc, ch4_conc, n2o_conc
        Concentration arrays matching years
    config
        MAGICC config dictionary with forcing method and parameters

    Returns
    -------
    Model ready to run
    """
    # Map MAGICC config to GhgForcing parameters
    rf_method = config.get("core_co2ch4n2o_rfmethod", "IPCCTAR")
    if rf_method == "IPCCTAR":
        method = "Ipcctar"
        # IPCCTAR typically has no rapid adjustment
        adjust_co2 = config.get("core_rfrapidadjust_co2", 1.0)
        adjust_ch4 = config.get("core_rfrapidadjust_ch4", 1.0)
        adjust_n2o = config.get("core_rfrapidadjust_n2o", 1.0)
    elif rf_method == "OLBL":
        method = "Olbl"
        adjust_co2 = config.get("core_rfrapidadjust_co2", 1.05)
        adjust_ch4 = config.get("core_rfrapidadjust_ch4", 0.86)
        adjust_n2o = config.get("core_rfrapidadjust_n2o", 1.0)
    else:
        msg = f"Unsupported forcing method: {rf_method}"
        raise ValueError(msg)

    # MAGICC7 uses the first-year concentrations as the pre-industrial
    # reference, not fixed values like 278.0 ppm. This ensures forcing
    # is exactly zero at the start of the simulation.
    ghg_params = {
        "method": method,
        "delq2xco2": config.get("core_delq2xco2", 3.71),
        "co2_pi": float(co2_conc[0]),
        "ch4_pi": float(ch4_conc[0]),
        "n2o_pi": float(n2o_conc[0]),
        "adjust_co2": adjust_co2,
        "adjust_ch4": adjust_ch4,
        "adjust_n2o": adjust_n2o,
    }

    ghg_component = GhgForcingBuilder.from_parameters(ghg_params).build()

    # Create time axis from year values
    # years are annual (e.g. 1750, 1751, ..., 2100)
    # TimeAxis needs bounds: one more value than data points
    time_axis = TimeAxis.from_bounds(
        np.concatenate([years, [years[-1] + 1.0]]).astype(np.float64)
    )

    # Create concentration timeseries
    co2_ts = Timeseries(
        co2_conc.astype(np.float64),
        time_axis,
        "ppm",
        InterpolationStrategy.Linear,
    )
    ch4_ts = Timeseries(
        ch4_conc.astype(np.float64),
        time_axis,
        "ppb",
        InterpolationStrategy.Linear,
    )
    n2o_ts = Timeseries(
        n2o_conc.astype(np.float64),
        time_axis,
        "ppb",
        InterpolationStrategy.Linear,
    )

    model = (
        ModelBuilder()
        .with_time_axis(time_axis)
        .with_rust_component(ghg_component)
        .with_exogenous_variable("Atmospheric Concentration|CO2", co2_ts)
        .with_exogenous_variable("Atmospheric Concentration|CH4", ch4_ts)
        .with_exogenous_variable("Atmospheric Concentration|N2O", n2o_ts)
        .build()
    )

    return model


def test_01_concentration_driven():
    """
    Test 1: Concentration-driven run with IPCCTAR forcing method.

    Validates GHG forcing calculation using SSP245 concentration pathways.
    Uses IPCCTAR radiative forcing method for simpler validation.

    Variables compared:
    - Effective Radiative Forcing|CO2/CH4/N2O

    Note: Surface Temperature comparison requires ClimateUDEB integration
    which needs scalar-to-FourBox bridging (not yet implemented).
    """
    df, config = load_regression_data("01_concentration_driven")

    # Verify config matches expected
    assert config.get("core_co2ch4n2o_rfmethod") == "IPCCTAR"
    assert config.get("core_climatesensitivity") == 3.0

    # Extract concentration inputs
    years, co2_conc = get_variable_values(df, "Atmospheric Concentrations|CO2")
    _, ch4_conc = get_variable_values(df, "Atmospheric Concentrations|CH4")
    _, n2o_conc = get_variable_values(df, "Atmospheric Concentrations|N2O")

    # Extract expected forcing outputs
    _, expected_erf_co2 = get_variable_values(df, "Effective Radiative Forcing|CO2")
    _, expected_erf_ch4 = get_variable_values(df, "Effective Radiative Forcing|CH4")
    _, expected_erf_n2o = get_variable_values(df, "Effective Radiative Forcing|N2O")

    # Build and run model
    model = build_ghg_forcing_model(years, co2_conc, ch4_conc, n2o_conc, config)
    model.run()

    results = model.timeseries()

    # Extract actual forcing outputs
    # The model outputs NaN at index 0 (initial state) and writes solve
    # results starting at index 1. So actual[1:] aligns with expected[:-1].
    actual_erf_co2 = results.get_timeseries_by_name(
        "Effective Radiative Forcing|CO2"
    ).values()[1:]
    actual_erf_ch4 = results.get_timeseries_by_name(
        "Effective Radiative Forcing|CH4"
    ).values()[1:]
    actual_erf_n2o = results.get_timeseries_by_name(
        "Effective Radiative Forcing|N2O"
    ).values()[1:]

    # Compare ERF outputs against MAGICC7 reference
    npt.assert_allclose(
        actual_erf_co2,
        expected_erf_co2[:-1],
        rtol=DEFAULT_RTOL,
        atol=DEFAULT_ATOL,
        err_msg="CO2 ERF mismatch (IPCCTAR method)",
    )
    npt.assert_allclose(
        actual_erf_ch4,
        expected_erf_ch4[:-1],
        rtol=DEFAULT_RTOL,
        atol=DEFAULT_ATOL,
        err_msg="CH4 ERF mismatch (IPCCTAR method)",
    )
    npt.assert_allclose(
        actual_erf_n2o,
        expected_erf_n2o[:-1],
        rtol=DEFAULT_RTOL,
        atol=DEFAULT_ATOL,
        err_msg="N2O ERF mismatch (IPCCTAR method)",
    )


def test_02_ghg_forcing_olbl():
    """
    Test 2: GHG forcing with OLBL method.

    Validates GHG forcing calculation using the modern OLBL (Optimal Linear
    Basis Level) method with rapid adjustment factors, as used in AR6.

    Config:
    - core_co2ch4n2o_rfmethod: OLBL
    - Rapid adjustment factors: CO2=1.05, CH4=0.86, N2O=0.93

    Variables compared:
    - Effective Radiative Forcing|CO2/CH4/N2O

    Note: Surface Temperature comparison requires ClimateUDEB integration
    which needs scalar-to-FourBox bridging (not yet implemented).
    """
    df, config = load_regression_data("02_ghg_forcing_olbl")

    # Verify config matches expected
    assert config.get("core_co2ch4n2o_rfmethod") == "OLBL"
    assert config.get("core_rfrapidadjust_co2") == 1.05
    assert config.get("core_rfrapidadjust_ch4") == 0.86
    assert config.get("core_rfrapidadjust_n2o") == 0.93

    # Extract concentration inputs
    years, _ = get_variable_values(df, "Effective Radiative Forcing|CO2")
    _, co2_conc = get_variable_values(df, "Atmospheric Concentrations|CO2")
    _, ch4_conc = get_variable_values(df, "Atmospheric Concentrations|CH4")
    _, n2o_conc = get_variable_values(df, "Atmospheric Concentrations|N2O")

    # Extract expected forcing outputs
    _, expected_erf_co2 = get_variable_values(df, "Effective Radiative Forcing|CO2")
    _, expected_erf_ch4 = get_variable_values(df, "Effective Radiative Forcing|CH4")
    _, expected_erf_n2o = get_variable_values(df, "Effective Radiative Forcing|N2O")

    # Build and run model
    model = build_ghg_forcing_model(years, co2_conc, ch4_conc, n2o_conc, config)
    model.run()

    results = model.timeseries()

    # Extract actual forcing outputs (skip index 0 = NaN initial state)
    actual_erf_co2 = results.get_timeseries_by_name(
        "Effective Radiative Forcing|CO2"
    ).values()[1:]
    actual_erf_ch4 = results.get_timeseries_by_name(
        "Effective Radiative Forcing|CH4"
    ).values()[1:]
    actual_erf_n2o = results.get_timeseries_by_name(
        "Effective Radiative Forcing|N2O"
    ).values()[1:]

    # Compare ERF outputs against MAGICC7 reference
    npt.assert_allclose(
        actual_erf_co2,
        expected_erf_co2[:-1],
        rtol=DEFAULT_RTOL,
        atol=DEFAULT_ATOL,
        err_msg="CO2 ERF mismatch (OLBL method)",
    )
    npt.assert_allclose(
        actual_erf_ch4,
        expected_erf_ch4[:-1],
        rtol=DEFAULT_RTOL,
        atol=DEFAULT_ATOL,
        err_msg="CH4 ERF mismatch (OLBL method)",
    )
    npt.assert_allclose(
        actual_erf_n2o,
        expected_erf_n2o[:-1],
        rtol=DEFAULT_RTOL,
        atol=DEFAULT_ATOL,
        err_msg="N2O ERF mismatch (OLBL method)",
    )


def _build_emissions_schema():
    """Build the VariableSchema for a full emissions-driven MAGICC model."""
    schema = VariableSchema()

    # Concentration variables
    schema.add_variable("Atmospheric Concentration|CO2", "ppm")
    schema.add_variable("Atmospheric Concentration|CH4", "ppb")
    schema.add_variable("Atmospheric Concentration|N2O", "ppb")

    # Emission variables
    schema.add_variable("Emissions|CO2|Fossil", "GtC/yr")
    schema.add_variable("Emissions|CO2|Land Use", "GtC/yr")
    schema.add_variable("Emissions|CH4", "Mt CH4/yr")
    schema.add_variable("Emissions|N2O", "Mt N/yr")
    schema.add_variable("Emissions|NOx", "Mt N/yr")
    schema.add_variable("Emissions|CO", "Mt CO/yr")
    schema.add_variable("Emissions|NMVOC", "Mt NMVOC/yr")
    schema.add_variable("Emissions|SOx", "Mt S/yr")
    schema.add_variable("Emissions|BC", "Mt BC/yr")
    schema.add_variable("Emissions|OC", "Mt OC/yr")
    schema.add_variable("EESC", "ppt")

    # Forcing variables
    schema.add_variable("Effective Radiative Forcing|CO2", "W/m^2")
    schema.add_variable("Effective Radiative Forcing|CH4", "W/m^2")
    schema.add_variable("Effective Radiative Forcing|N2O", "W/m^2")
    schema.add_variable("Effective Radiative Forcing|O3|Stratospheric", "W/m^2")
    schema.add_variable("Effective Radiative Forcing|O3|Tropospheric", "W/m^2")
    schema.add_variable("Effective Radiative Forcing|O3|Temperature Feedback", "W/m^2")
    schema.add_variable("Effective Radiative Forcing|Aerosol|Direct", "W/m^2")
    schema.add_variable("Effective Radiative Forcing|Aerosol|Indirect", "W/m^2")

    # Climate variables
    schema.add_variable("Surface Temperature", "K", GridType.FourBox)
    schema.add_variable("Heat Uptake", "W/m^2")
    schema.add_variable("Ocean Heat Content", "J/m^2")
    schema.add_variable("Sea Surface Temperature", "K")

    # Carbon cycle variables
    schema.add_variable("Carbon Flux|Terrestrial", "GtC/yr")
    schema.add_variable("Carbon Flux|Ocean", "GtC/yr")
    schema.add_variable("Carbon Pool|Plant", "GtC")
    schema.add_variable("Carbon Pool|Detritus", "GtC")
    schema.add_variable("Carbon Pool|Soil", "GtC")
    schema.add_variable("Carbon Pool|Humus", "GtC")
    schema.add_variable("Ocean Surface pCO2", "ppm")
    schema.add_variable("Cumulative Ocean Uptake", "GtC")
    schema.add_variable("Emissions|CO2|Net", "GtC/yr")
    schema.add_variable("Airborne Fraction|CO2", "1")
    schema.add_variable("Lifetime|CH4", "yr")
    schema.add_variable("Lifetime|N2O", "yr")

    # ERF aggregation
    schema.add_aggregate(
        "Effective Radiative Forcing",
        "W/m^2",
        "Sum",
        [
            "Effective Radiative Forcing|CO2",
            "Effective Radiative Forcing|CH4",
            "Effective Radiative Forcing|N2O",
            "Effective Radiative Forcing|O3|Stratospheric",
            "Effective Radiative Forcing|O3|Tropospheric",
            "Effective Radiative Forcing|O3|Temperature Feedback",
            "Effective Radiative Forcing|Aerosol|Direct",
            "Effective Radiative Forcing|Aerosol|Indirect",
        ],
    )

    return schema


def build_emissions_driven_model(
    years,
    emissions,
    initial_conditions,
    config,
):
    """
    Build a full emissions-driven MAGICC model.

    Parameters
    ----------
    years
        Array of year values (1750-2100)
    emissions
        Dict mapping variable name -> (values_array, unit_string)
    initial_conditions
        Dict mapping state variable name -> initial value (float)
    config
        MAGICC config dict

    Returns
    -------
    Model ready to run
    """
    time_axis = TimeAxis.from_bounds(
        np.concatenate([years, [years[-1] + 1.0]]).astype(np.float64)
    )

    # Build components with default parameters
    ghg = GhgForcingBuilder.from_parameters(
        {
            "method": "Ipcctar",
            "delq2xco2": config.get("core_delq2xco2", 3.71),
            "co2_pi": initial_conditions.get("Atmospheric Concentration|CO2", 278.0),
            "ch4_pi": initial_conditions.get("Atmospheric Concentration|CH4", 700.0),
            "n2o_pi": initial_conditions.get("Atmospheric Concentration|N2O", 270.0),
        }
    ).build()

    climate = ClimateUDEBBuilder.from_parameters(
        {
            "ecs": config.get("core_climatesensitivity", 3.0),
            "forcing_2xco2": config.get("core_delq2xco2", 3.71),
        }
    ).build()

    ch4_chem = CH4ChemistryBuilder.from_parameters(
        {
            "ch4_pi": initial_conditions.get("Atmospheric Concentration|CH4", 722.0),
        }
    ).build()
    n2o_chem = N2OChemistryBuilder.from_parameters(
        {
            "n2o_pi": initial_conditions.get("Atmospheric Concentration|N2O", 270.0),
        }
    ).build()
    terrestrial = TerrestrialCarbonBuilder.from_parameters({}).build()
    ocean = OceanCarbonBuilder.from_parameters({}).build()
    co2_budget = CO2BudgetBuilder.from_parameters({}).build()
    ozone = OzoneForcingBuilder.from_parameters({}).build()
    aerosol_direct = AerosolDirectBuilder.from_parameters({}).build()
    aerosol_indirect = AerosolIndirectBuilder.from_parameters({}).build()

    schema = _build_emissions_schema()

    # Wire components
    builder = (
        ModelBuilder()
        .with_time_axis(time_axis)
        .with_schema(schema)
        .with_rust_component(ch4_chem)
        .with_rust_component(n2o_chem)
        .with_rust_component(ghg)
        .with_rust_component(ozone)
        .with_rust_component(aerosol_direct)
        .with_rust_component(aerosol_indirect)
        .with_rust_component(climate)
        .with_rust_component(terrestrial)
        .with_rust_component(ocean)
        .with_rust_component(co2_budget)
    )

    # Add exogenous emissions timeseries
    for var_name, (values, unit) in emissions.items():
        ts = Timeseries(
            values.astype(np.float64),
            time_axis,
            unit,
            InterpolationStrategy.Linear,
        )
        builder = builder.with_exogenous_variable(var_name, ts)

    # Set initial conditions for all state variables
    builder = builder.with_initial_values(initial_conditions)

    return builder.build()


def _extract_emissions(df, years):
    """Extract emissions from MAGICC reference data, summing sector splits."""
    emissions = {}

    def _get_or_zero(var, unit):
        try:
            _, vals = get_variable_values(df, var)
        except ValueError:
            return np.zeros_like(years, dtype=np.float64)
        else:
            return vals

    def _sum_sectors(base_var, unit):
        total = np.zeros_like(years, dtype=np.float64)
        for sector in ["MAGICC Fossil and Industrial", "MAGICC AFOLU"]:
            total += _get_or_zero(f"{base_var}|{sector}", unit)
        return (total, unit)

    # CO2: total available, assign all to fossil (no LU split in output)
    co2_unit = "GtC/yr"
    emissions["Emissions|CO2|Fossil"] = (
        _get_or_zero("Emissions|CO2", co2_unit),
        co2_unit,
    )
    emissions["Emissions|CO2|Land Use"] = (
        np.zeros_like(years, dtype=np.float64),
        co2_unit,
    )

    # CH4 and N2O totals
    emissions["Emissions|CH4"] = (
        _get_or_zero("Emissions|CH4", "Mt CH4/yr"),
        "Mt CH4/yr",
    )
    emissions["Emissions|N2O"] = (
        _get_or_zero("Emissions|N2O", "Mt N/yr"),
        "Mt N/yr",
    )

    # Species emissions: sum MAGICC sectors
    for var, unit in [
        ("Emissions|NOx", "Mt N/yr"),
        ("Emissions|CO", "Mt CO/yr"),
        ("Emissions|NMVOC", "Mt NMVOC/yr"),
        ("Emissions|SOx", "Mt S/yr"),
        ("Emissions|BC", "Mt BC/yr"),
        ("Emissions|OC", "Mt OC/yr"),
    ]:
        emissions[var] = _sum_sectors(var, unit)

    # No halocarbons wired
    emissions["EESC"] = (np.zeros_like(years, dtype=np.float64), "ppt")

    return emissions


@pytest.mark.xfail(
    reason="Diverges from MAGICC7 due to documented simplifications (#108, #109, #110)"
)
def test_03_emissions_driven():
    """
    Test 3: Emissions-driven run with full carbon cycle.

    Validates the complete emissions -> concentrations -> forcing -> temperature
    pathway using SSP245 emissions scenario.

    Variables compared:
    - Atmospheric Concentrations|CO2/CH4/N2O (calculated from emissions)
    - Surface Temperature
    """
    df, config = load_regression_data("03_emissions_driven")

    # Extract expected outputs (MAGICC uses plural "Concentrations")
    years, expected_co2_conc = get_variable_values(df, "Atmospheric Concentrations|CO2")
    _, expected_ch4_conc = get_variable_values(df, "Atmospheric Concentrations|CH4")
    _, expected_n2o_conc = get_variable_values(df, "Atmospheric Concentrations|N2O")
    _, expected_temp = get_variable_values(df, "Surface Temperature")

    emissions = _extract_emissions(df, years)

    # Initial conditions for all state variables
    initial_conditions = {
        # Concentrations from first-year reference values
        "Atmospheric Concentration|CO2": float(expected_co2_conc[0]),
        "Atmospheric Concentration|CH4": float(expected_ch4_conc[0]),
        "Atmospheric Concentration|N2O": float(expected_n2o_conc[0]),
        # Climate starts at zero anomaly
        "Surface Temperature": 0.0,
        # Ocean carbon: pCO2 starts near atmospheric, cumulative uptake at 0
        "Ocean Surface pCO2": float(expected_co2_conc[0]),
        "Cumulative Ocean Uptake": 0.0,
        # Terrestrial carbon pools: PI defaults from TerrestrialCarbonParameters
        "Carbon Pool|Plant": 884.86,
        "Carbon Pool|Detritus": 92.77,
        "Carbon Pool|Soil": 1681.53,
        "Carbon Pool|Humus": 836.0,
    }

    model = build_emissions_driven_model(years, emissions, initial_conditions, config)
    model.run()

    results = model.timeseries()

    # Relaxed tolerances for initial wiring validation
    # Tighter tolerances require physics refinements tracked in #108, #109, #110
    emissions_rtol = 5e-2  # 5% relative tolerance

    # Compare CO2 concentration (RSCM uses singular "Concentration")
    actual_co2 = results.get_timeseries_by_name(
        "Atmospheric Concentration|CO2"
    ).values()[1:]
    npt.assert_allclose(
        actual_co2,
        expected_co2_conc[:-1],
        rtol=emissions_rtol,
        atol=DEFAULT_ATOL,
        err_msg="CO2 concentration mismatch",
    )

    # Compare CH4 concentration
    actual_ch4 = results.get_timeseries_by_name(
        "Atmospheric Concentration|CH4"
    ).values()[1:]
    npt.assert_allclose(
        actual_ch4,
        expected_ch4_conc[:-1],
        rtol=emissions_rtol,
        atol=DEFAULT_ATOL,
        err_msg="CH4 concentration mismatch",
    )

    # Compare N2O concentration
    actual_n2o = results.get_timeseries_by_name(
        "Atmospheric Concentration|N2O"
    ).values()[1:]
    npt.assert_allclose(
        actual_n2o,
        expected_n2o_conc[:-1],
        rtol=emissions_rtol,
        atol=DEFAULT_ATOL,
        err_msg="N2O concentration mismatch",
    )

    # Compare Sea Surface Temperature (scalar proxy for global mean)
    actual_sst = results.get_timeseries_by_name("Sea Surface Temperature").values()[1:]
    npt.assert_allclose(
        actual_sst,
        expected_temp[:-1],
        rtol=emissions_rtol,
        atol=DEFAULT_ATOL,
        err_msg="Temperature mismatch",
    )


@pytest.mark.skip(
    reason="Requires scalar-to-FourBox bridging for ClimateUDEB integration"
)
@pytest.mark.parametrize("ecs", [1.5, 2.0, 3.0, 4.0, 4.5])
def test_04_ecs_sweep(ecs: float):
    """
    Test 4: Climate sensitivity parameter sweep.

    Validates climate response for different Equilibrium Climate Sensitivity
    (ECS) values ranging from 1.5K to 4.5K using SSP245 CO2 concentration
    pathway.

    Parameters
    ----------
    ecs
        Equilibrium Climate Sensitivity value in Kelvin

    Variables compared:
    - Surface Temperature (primary validation target)
    - Effective Radiative Forcing|CO2 (should be identical across ECS values)
    """
    df, config = load_regression_data(f"04_ecs_sweep_{ecs}")

    # Verify config matches expected ECS
    assert config.get("core_climatesensitivity") == ecs

    # Extract expected values
    years, expected_temp = get_variable_values(df, "Surface Temperature")
    _, _expected_erf_co2 = get_variable_values(df, "Effective Radiative Forcing|CO2")

    # Verify data was loaded
    assert len(years) > 0
    assert len(expected_temp) == len(years)


@pytest.mark.skip(
    reason="Requires scalar-to-FourBox bridging for ClimateUDEB integration"
)
def test_05_co2_only_forcing():
    """
    Test 5: CO2-only forcing mode.

    Validates that total forcing equals CO2 forcing when running in CO2-only
    mode. This isolates the CO2 forcing pathway for clean validation.

    Config:
    - rf_total_runmodus: CO2 (only CO2 forcing contributes)

    Variables compared:
    - Effective Radiative Forcing (total should equal CO2 forcing)
    - Effective Radiative Forcing|CO2
    - Surface Temperature
    """
    df, config = load_regression_data("05_co2_only_forcing")

    # Verify config
    assert config.get("rf_total_runmodus") == "CO2"

    # Extract expected values
    years, expected_total_erf = get_variable_values(df, "Effective Radiative Forcing")
    _, expected_erf_co2 = get_variable_values(df, "Effective Radiative Forcing|CO2")
    _, _expected_temp = get_variable_values(df, "Surface Temperature")

    # Verify data was loaded
    assert len(years) > 0

    # In CO2-only mode, total ERF should equal CO2 ERF
    # (This is a sanity check on the reference data)
    npt.assert_allclose(expected_total_erf, expected_erf_co2, rtol=1e-6)
