"""
Terrestrial carbon cycle RSCM-vs-MAGICC7 parity tests.

Drives the RSCM TerrestrialCarbon component with the same inputs
(CO2 concentration, temperature, land-use emissions) that MAGICC7 used,
and compares output trajectories year-by-year.

Reference data generated by:
    scripts/regression/generate_terrestrial_carbon.py

Run with:
    uv run pytest tests/regression/test_terrestrial_parity.py -v --nocapture
"""

from __future__ import annotations

from typing import ClassVar

import numpy as np
import pytest

from regression.helpers import (
    get_variable_values,
    load_regression_data,
)
from rscm._lib.core import (
    InterpolationStrategy,
    ModelBuilder,
    TimeAxis,
    Timeseries,
    VariableSchema,
)
from rscm.magicc import TerrestrialCarbonBuilder

SUITE = "terrestrial_carbon"


def _load(name: str):
    return load_regression_data(SUITE, name)


def _build_terrestrial_model(  # noqa: PLR0913
    years: np.ndarray,
    co2: np.ndarray,
    temperature: np.ndarray,
    landuse: np.ndarray,
    initial_pools: dict[str, float],
    params: dict | None = None,
):
    """Build a Model with just TerrestrialCarbon driven by exogenous inputs.

    Parameters
    ----------
    years
        Year array (start-of-year values, e.g. [1750, 1751, ..., 2100])
    co2
        CO2 concentration timeseries (ppm), same length as years
    temperature
        Surface temperature anomaly (K), same length as years
    landuse
        Land-use CO2 emissions (GtC/yr), same length as years
    initial_pools
        Initial pool sizes, keyed by variable name
    params
        Optional TerrestrialCarbonParameters overrides
    """
    if params is None:
        params = {}

    # Time axis needs bounds (N+1 values for N steps)
    bounds = np.concatenate([years, [years[-1] + 1.0]]).astype(np.float64)
    time_axis = TimeAxis.from_bounds(bounds)

    # Build component
    terrestrial = TerrestrialCarbonBuilder.from_parameters(params).build()

    # Schema: declare all variables
    schema = VariableSchema()
    schema.add_variable("Atmospheric Concentration|CO2", "ppm")
    schema.add_variable("Surface Temperature", "K")
    schema.add_variable("Emissions|CO2|Land Use", "GtC/yr")
    schema.add_variable("Carbon Pool|Plant", "GtC")
    schema.add_variable("Carbon Pool|Detritus", "GtC")
    schema.add_variable("Carbon Pool|Soil", "GtC")
    schema.add_variable("Carbon Flux|Terrestrial", "GtC/yr")
    schema.add_variable("Emissions|CO2|Gross Deforestation", "GtC/yr")
    schema.add_variable("Carbon Flux|Regrowth", "GtC/yr")
    schema.add_variable("Net Primary Production", "GtC/yr")
    schema.add_variable("Respiration|Terrestrial", "GtC/yr")

    builder = (
        ModelBuilder()
        .with_time_axis(time_axis)
        .with_schema(schema)
        .with_rust_component(terrestrial)
    )

    # Add exogenous driving inputs
    for var_name, values in [
        ("Atmospheric Concentration|CO2", co2),
        ("Surface Temperature", temperature),
        ("Emissions|CO2|Land Use", landuse),
    ]:
        ts = Timeseries(
            values.astype(np.float64),
            time_axis,
            "ppm"
            if "CO2" in var_name and "Emission" not in var_name
            else ("K" if "Temp" in var_name else "GtC/yr"),
            InterpolationStrategy.Linear,
        )
        builder = builder.with_exogenous_variable(var_name, ts)

    builder = builder.with_initial_values(initial_pools)

    return builder.build()


def _run_parity_test(
    test_name: str,
    params: dict | None = None,
    co2_var: str = "Atmospheric Concentrations|CO2",
    temp_var: str = "Surface Temperature",
    landuse_var: str = "Emissions|CO2|Land Use",
):
    """Run RSCM and compare against MAGICC7 reference data.

    Returns (rscm_results, magicc_ref_df) for further assertions.
    """
    df, _cfg = _load(test_name)

    # Extract driving inputs from reference data
    years_co2, co2_vals = get_variable_values(df, co2_var)
    try:
        _, temp_vals = get_variable_values(df, temp_var)
    except Exception:
        # No temperature in reference data (e.g., concentration-driven)
        temp_vals = np.zeros_like(co2_vals)

    try:
        _, lu_vals = get_variable_values(df, landuse_var)
    except Exception:
        lu_vals = np.zeros_like(co2_vals)

    # Exclude last year (MAGICC boundary artifact with zeros)
    years = years_co2[:-1]
    co2 = co2_vals[:-1]
    temp = temp_vals[:-1]
    lu = lu_vals[:-1]

    # Initial pool sizes from reference data
    _, plant_ref = get_variable_values(df, "Carbon Pool|Plant")
    _, detritus_ref = get_variable_values(df, "Carbon Pool|Detritus")
    _, soil_ref = get_variable_values(df, "Carbon Pool|Soil")

    initial_pools = {
        "Carbon Pool|Plant": float(plant_ref[0]),
        "Carbon Pool|Detritus": float(detritus_ref[0]),
        "Carbon Pool|Soil": float(soil_ref[0]),
    }

    # Build and run
    model = _build_terrestrial_model(years, co2, temp, lu, initial_pools, params=params)
    model.run()
    results = model.timeseries()

    return results, df, years


def _get_rscm_values(results, var_name: str) -> np.ndarray:
    """Extract values from RSCM TimeseriesCollection."""
    ts = results.get_timeseries_by_name(var_name)
    return np.array(ts.values())


def _compare_variable(  # noqa: PLR0913
    results,
    df,
    years,
    var_name: str,
    rtol: float = 0.20,
    label: str = "",
) -> float:
    """Compare RSCM output against MAGICC7 reference for a variable.

    Returns the max relative error.
    """
    _, ref_vals = get_variable_values(df, var_name)
    ref_vals = ref_vals[:-1]  # Exclude MAGICC boundary artifact

    rscm_vals = _get_rscm_values(results, var_name)

    # RSCM has N+1 values (initial + N steps), ref has N values (years)
    # Align: RSCM values at each year boundary
    n = min(len(rscm_vals), len(ref_vals))
    rscm_vals = rscm_vals[:n]
    ref_vals = ref_vals[:n]

    # Filter out NaN (output variables have NaN before first solve)
    # and near-zero reference values
    mask = np.isfinite(rscm_vals) & np.isfinite(ref_vals) & (np.abs(ref_vals) > 1e-6)
    if not np.any(mask):
        return 0.0

    rel_err = np.abs((rscm_vals[mask] - ref_vals[mask]) / ref_vals[mask])
    max_err = float(rel_err.max())
    mean_err = float(rel_err.mean())

    tag = label or var_name
    first_valid = rscm_vals[mask][0] if np.any(mask) else float("nan")
    print(f"{tag}: max_rel_err={max_err:.4f}, mean={mean_err:.4f}")
    print(f"  RSCM:  [{first_valid:.2f} ... {rscm_vals[-1]:.2f}]")
    print(f"  MAGICC: [{ref_vals[0]:.2f} ... {ref_vals[-1]:.2f}]")

    assert max_err < rtol, (
        f"{tag} max relative error {max_err:.4f} exceeds {rtol * 100:.0f}%"
    )
    return max_err


@pytest.mark.slow
class TestCO2FertilizationParity:
    """Parity test 02: CO2 fertilization only (no temperature feedback)."""

    NAME = "02_co2_fertilization_only"
    PARAMS: ClassVar[dict] = {
        "fertilization_method": 1.10,
        "tempfeedback_yrstart": 9999.0,
    }

    def test_plant_pool(self):
        results, df, years = _run_parity_test(self.NAME, params=self.PARAMS)
        _compare_variable(results, df, years, "Carbon Pool|Plant", rtol=0.20)

    def test_detritus_pool(self):
        results, df, years = _run_parity_test(self.NAME, params=self.PARAMS)
        _compare_variable(results, df, years, "Carbon Pool|Detritus", rtol=0.20)

    def test_soil_pool(self):
        results, df, years = _run_parity_test(self.NAME, params=self.PARAMS)
        _compare_variable(results, df, years, "Carbon Pool|Soil", rtol=0.20)

    def test_npp(self):
        results, df, years = _run_parity_test(self.NAME, params=self.PARAMS)
        _compare_variable(results, df, years, "Net Primary Production", rtol=0.20)


@pytest.mark.slow
class TestCO2AndTempParity:
    """Parity test 03: CO2 + temperature feedbacks."""

    NAME = "03_co2_and_temperature"
    PARAMS: ClassVar[dict] = {
        "fertilization_method": 1.10,
    }

    def test_plant_pool(self):
        results, df, years = _run_parity_test(self.NAME, params=self.PARAMS)
        _compare_variable(results, df, years, "Carbon Pool|Plant", rtol=0.30)

    def test_npp(self):
        results, df, years = _run_parity_test(self.NAME, params=self.PARAMS)
        _compare_variable(results, df, years, "Net Primary Production", rtol=0.30)


@pytest.mark.slow
class TestGiffordParity:
    """Parity test 05: Gifford fertilization method."""

    NAME = "05_gifford_fertilization"
    PARAMS: ClassVar[dict] = {
        "fertilization_method": 2.0,
        "tempfeedback_yrstart": 9999.0,
    }

    def test_plant_pool(self):
        results, df, years = _run_parity_test(self.NAME, params=self.PARAMS)
        _compare_variable(results, df, years, "Carbon Pool|Plant", rtol=0.20)

    def test_npp(self):
        results, df, years = _run_parity_test(self.NAME, params=self.PARAMS)
        _compare_variable(results, df, years, "Net Primary Production", rtol=0.20)
