"""
Terrestrial carbon cycle regression tests.

Validates MAGICC7 reference data for the terrestrial carbon cycle
(CARBONCYCLE.OUT) and establishes baselines for future RSCM parity testing.

Test scenarios:
    01: Pre-industrial steady state (constant CO2 at 284.32 ppm)
    02: CO2 fertilization only (SSP245 concentrations, temp feedback off)
    03: CO2 + temperature feedbacks (SSP245 concentrations)
    04: Full emissions-driven (SSP245 with all feedbacks and land-use)
    05: Gifford fertilization method (method=2.0)
    06: Respiration method 2

Reference data generated by:
    scripts/regression/generate_terrestrial_carbon.py

Run with:
    uv run pytest tests/regression/test_terrestrial_carbon.py -v --nocapture
"""

from __future__ import annotations

import numpy as np
import pytest

from regression.helpers import (
    get_variable_values,
    load_regression_data,
)

SUITE = "terrestrial_carbon"


def _load(name: str):
    """Load reference data, skipping if not generated yet."""
    return load_regression_data(SUITE, name)


def _get(df, var):
    """Get variable values, excluding the final row (MAGICC boundary artifact)."""
    years, values = get_variable_values(df, var)
    # MAGICC CARBONCYCLE.OUT writes zeros in the last row for some diagnostics
    return years[:-1], values[:-1]


class TestPISteadyState:
    """Test 01: Pre-industrial steady state.

    At constant CO2 (284.32 ppm, the 1850 value) with no land-use emissions,
    pools should be approximately stable. Note: the 1850 CO2 file uses 284.32 ppm
    which is slightly above MAGICC's default PI of 278 ppm, causing a small
    fertilization-driven drift.
    """

    NAME = "01_pi_steady_state"

    def test_plant_pool_stable(self):
        df, _cfg = _load(self.NAME)
        _years, values = _get(df, "Carbon Pool|Plant")
        initial = values[0]
        drift_pct = np.abs((values - initial) / initial * 100).max()
        assert drift_pct < 2.0, f"Plant pool drifted {drift_pct:.4f}% from initial"

    def test_detritus_pool_stable(self):
        df, _cfg = _load(self.NAME)
        _years, values = _get(df, "Carbon Pool|Detritus")
        initial = values[0]
        drift_pct = np.abs((values - initial) / initial * 100).max()
        assert drift_pct < 1.0, f"Detritus pool drifted {drift_pct:.4f}% from initial"

    def test_soil_pool_stable(self):
        df, _cfg = _load(self.NAME)
        _years, values = _get(df, "Carbon Pool|Soil")
        initial = values[0]
        drift_pct = np.abs((values - initial) / initial * 100).max()
        assert drift_pct < 0.5, f"Soil pool drifted {drift_pct:.4f}% from initial"

    def test_npp_constant(self):
        df, _cfg = _load(self.NAME)
        _years, values = _get(df, "Net Primary Production")
        std = np.std(values)
        assert std < 0.1, f"NPP should be approximately constant, std={std:.4f}"

    def test_fertilization_factor_near_unity(self):
        """Fertilization factor near 1.0 (CO2=284 vs PI=278)."""
        df, _cfg = _load(self.NAME)
        _years, values = _get(df, "CO2 Fertilization Factor")
        np.testing.assert_allclose(
            values,
            1.0,
            atol=0.02,
            err_msg="Fertilization factor should be near 1.0 at ~PI CO2",
        )

    def test_delta_terrpools_small(self):
        df, _cfg = _load(self.NAME)
        _years, values = _get(df, "Carbon Flux|Terrestrial")
        assert np.abs(values).max() < 0.5, (
            f"Net terrestrial flux should be small at near-PI: "
            f"max abs = {np.abs(values).max():.4f} GtC/yr"
        )


class TestCO2FertilizationOnly:
    """Test 02: CO2 fertilization response without temperature feedbacks.

    With SSP245 CO2 concentrations and temperature feedbacks disabled,
    the land sink should grow as CO2 rises.
    """

    NAME = "02_co2_fertilization_only"

    def test_fertilization_factor_increases(self):
        df, _cfg = _load(self.NAME)
        _years, values = _get(df, "CO2 Fertilization Factor")
        assert values[-1] > values[0], (
            f"Fertilization factor should increase: {values[0]:.4f} -> {values[-1]:.4f}"
        )

    def test_npp_increases_with_co2(self):
        df, _cfg = _load(self.NAME)
        _years, values = _get(df, "Net Primary Production")
        early_mean = values[:10].mean()
        late_mean = values[-10:].mean()
        assert late_mean > early_mean, (
            f"NPP should increase with CO2: "
            f"early={early_mean:.2f}, late={late_mean:.2f}"
        )

    def test_pools_grow(self):
        df, _cfg = _load(self.NAME)
        for pool_name in [
            "Carbon Pool|Plant",
            "Carbon Pool|Detritus",
            "Carbon Pool|Soil",
        ]:
            _years, values = _get(df, pool_name)
            assert values[-1] > values[0], (
                f"{pool_name} should grow under elevated CO2: "
                f"{values[0]:.2f} -> {values[-1]:.2f}"
            )

    def test_temp_factors_unity(self):
        df, _cfg = _load(self.NAME)
        for var in [
            "Temperature Factor|NPP",
            "Temperature Factor|Respiration",
            "Temperature Factor|Detritus",
            "Temperature Factor|Soil",
        ]:
            _years, values = _get(df, var)
            np.testing.assert_allclose(
                values,
                1.0,
                atol=1e-6,
                err_msg=f"{var} should be 1.0 with temp feedback disabled",
            )


class TestCO2AndTemperature:
    """Test 03: CO2 fertilization + temperature feedbacks.

    Temperature feedbacks should increase respiration and reduce the
    net land sink compared to the CO2-only case.
    """

    NAME = "03_co2_and_temperature"

    def test_temp_factors_diverge_from_unity(self):
        df, _cfg = _load(self.NAME)
        _years, resp_factor = _get(df, "Temperature Factor|Respiration")
        assert resp_factor[-1] > 1.0, (
            f"Respiration temp factor should exceed 1.0 under warming: "
            f"{resp_factor[-1]:.4f}"
        )

    def test_warming_reduces_sink_vs_no_temp(self):
        try:
            df_no_temp, _ = _load("02_co2_fertilization_only")
            df_with_temp, _ = _load(self.NAME)
        except Exception:
            pytest.skip("Requires both test 02 and 03 reference data")

        _, pools_no_temp = _get(df_no_temp, "Carbon Pool|Plant")
        _, pools_with_temp = _get(df_with_temp, "Carbon Pool|Plant")

        assert pools_with_temp[-1] < pools_no_temp[-1], (
            f"Warming should reduce plant pool growth: "
            f"no_temp={pools_no_temp[-1]:.1f}, with_temp={pools_with_temp[-1]:.1f}"
        )

    def test_turnover_times_positive(self):
        df, _cfg = _load(self.NAME)
        for var in [
            "Turnover Time|Plant",
            "Turnover Time|Detritus",
            "Turnover Time|Soil",
        ]:
            _years, values = _get(df, var)
            assert np.all(values > 0), f"{var} should always be positive"


class TestEmissionsDriven:
    """Test 04: Full emissions-driven SSP245.

    Tests the full carbon cycle with land-use emissions, regrowth,
    time-varying turnover times, and all feedbacks.
    """

    NAME = "04_emissions_driven"

    def test_regrowth_positive(self):
        df, _cfg = _load(self.NAME)
        _years, values = _get(df, "Carbon Flux|Regrowth")
        late_values = values[50:]
        assert np.any(late_values > 0), (
            f"Regrowth should be positive under sustained deforestation, "
            f"max={late_values.max():.4f}"
        )

    def test_gross_defo_includes_regrowth(self):
        df, _cfg = _load(self.NAME)
        _years, regrowth = _get(df, "Carbon Flux|Regrowth")
        late_regrowth = regrowth[50:]
        assert np.any(late_regrowth > 0), "Expected positive regrowth in later years"

    def test_turnover_times_decrease(self):
        df, _cfg = _load(self.NAME)
        _years, tau_plant = _get(df, "Turnover Time|Plant")
        assert tau_plant[-1] < tau_plant[0], (
            f"Plant turnover time should decrease: "
            f"{tau_plant[0]:.2f} -> {tau_plant[-1]:.2f}"
        )

    def test_nofeedback_pools_diverge(self):
        df, _cfg = _load(self.NAME)
        _, main_plant = _get(df, "Carbon Pool|Plant")
        _, nf_plant = _get(df, "No-Feedback Pool|Plant")
        diff = main_plant[-1] - nf_plant[-1]
        assert abs(diff) > 1.0, (
            f"Main and no-feedback plant pools should diverge: "
            f"main={main_plant[-1]:.1f}, nf={nf_plant[-1]:.1f}, diff={diff:.1f}"
        )

    def test_pools_stay_positive(self):
        df, _cfg = _load(self.NAME)
        for pool_name in [
            "Carbon Pool|Plant",
            "Carbon Pool|Detritus",
            "Carbon Pool|Soil",
        ]:
            _years, values = _get(df, pool_name)
            assert np.all(values > 0), (
                f"{pool_name} went non-positive: min={values.min():.2f}"
            )


class TestGiffordFertilization:
    """Test 05: Gifford (Michaelis-Menten) fertilization method.

    Gifford fertilization should saturate at high CO2, producing a
    weaker land sink than logarithmic fertilization at high concentrations.
    """

    NAME = "05_gifford_fertilization"

    def test_fertilization_increases(self):
        """Gifford fertilization should increase with rising CO2."""
        df, _cfg = _load(self.NAME)
        _years, fert = _get(df, "CO2 Fertilization Factor")
        assert fert[-1] > fert[0], (
            f"Gifford fertilization should increase with CO2: "
            f"{fert[0]:.4f} -> {fert[-1]:.4f}"
        )

    def test_gifford_differs_from_default_blend(self):
        """Pure Gifford (method=2.0) should differ from default blend (method=1.10)."""
        try:
            df_blend, _ = _load("02_co2_fertilization_only")
            df_giff, _ = _load(self.NAME)
        except Exception:
            pytest.skip("Requires both test 02 and 05 reference data")

        _, fert_blend = _get(df_blend, "CO2 Fertilization Factor")
        _, fert_giff = _get(df_giff, "CO2 Fertilization Factor")
        diff = np.abs(fert_blend[-1] - fert_giff[-1])
        assert diff > 0.01, (
            f"Gifford and default blend should differ: "
            f"blend={fert_blend[-1]:.4f}, gifford={fert_giff[-1]:.4f}"
        )

    def test_gifford_factor_at_pi(self):
        df, _cfg = _load(self.NAME)
        _years, fert = _get(df, "CO2 Fertilization Factor")
        np.testing.assert_allclose(
            fert[0],
            1.0,
            atol=0.02,
            err_msg="Gifford fertilization should be near 1.0 at PI CO2",
        )


class TestRespirationMethod2:
    """Test 06: Plant-box-constrained respiration method.

    Method 2 constrains respiration by the plant pool ratio,
    producing different dynamics than method 1.
    """

    NAME = "06_resp_method2"

    def test_respiration_differs_from_method1(self):
        try:
            df_m1, _ = _load("03_co2_and_temperature")
            df_m2, _ = _load(self.NAME)
        except Exception:
            pytest.skip("Requires both test 03 and 06 reference data")

        _, resp_m1 = _get(df_m1, "Respiration|Terrestrial")
        _, resp_m2 = _get(df_m2, "Respiration|Terrestrial")
        late_diff = np.abs(resp_m1[-10:] - resp_m2[-10:]).mean()
        assert late_diff > 0.1, (
            f"Respiration methods should produce different results: "
            f"mean diff in last decade = {late_diff:.4f}"
        )

    def test_pools_remain_positive(self):
        df, _cfg = _load(self.NAME)
        for pool_name in [
            "Carbon Pool|Plant",
            "Carbon Pool|Detritus",
            "Carbon Pool|Soil",
        ]:
            _years, values = _get(df, pool_name)
            assert np.all(values > 0), (
                f"{pool_name} went non-positive: min={values.min():.2f}"
            )
