"""
Ocean physics regression tests.

Validates RSCM ClimateUDEB implementation against reference outputs
from Fortran MAGICC7, progressively enabling ocean physics features.

All scenarios use ABRUPT-2XCO2 forcing (step function: 0 at 1850,
then rf_2xco2 from 1851 onward) unless otherwise noted.

Reference data generated by:
  scripts/regression/generate_ocean_udeb.py

Test scenarios:
  01: Diffusion only (no upwelling)
  02: Constant upwelling (w_initial=3.5, variable_part=0)
  03: Depth-dependent ocean area (hypsometric profile)
  04: Variable upwelling (temperature-dependent shutdown)
  05: Temperature-dependent diffusivity (kappa_dkdt)
  06: Ground heat reservoir (land heat capacity damping)
  07: Inter-hemispheric heat exchange (k_ns)
  08: SST-to-SAT adjustment (short 10-year run)
  09: Time-varying ECS (feedback sensitivities)
  10: Full default configuration (1pctCO2 scenario)
"""

from __future__ import annotations

import numpy as np
import numpy.testing as npt
import pytest

from regression.helpers import (
    assert_allclose_phased,
    fourbox_global_mean,
    get_variable_values,
    load_regression_data,
)
from rscm._lib.core import (
    GridType,
    InterpolationStrategy,
    TimeAxis,
    Timeseries,
    VariableSchema,
)
from rscm._lib.magicc import ClimateUDEBBuilder
from rscm.core import ModelBuilder

SUITE = "ocean_udeb"
DEFAULT_ATOL = 1e-6
DEFAULT_RTOL = 3e-2


def load_data(name: str):
    return load_regression_data(SUITE, name)


def build_ocean_model(
    config: dict,
    erf_years: np.ndarray,
    erf_values: np.ndarray,
):
    """
    Build a ClimateUDEB model from a MAGICC ocean regression config.

    Maps MAGICC parameter names to RSCM ClimateUDEBParameters field names,
    constructs the component, wires exogenous ERF, and returns a model
    ready to run.

    Parameters
    ----------
    config
        MAGICC config dictionary with climate parameters
    erf_years
        Array of year values for the forcing timeseries
    erf_values
        Effective radiative forcing array (W/m^2) matching erf_years

    Returns
    -------
    Model ready to run
    """
    params = {
        "ecs": config.get("core_climatesensitivity", 3.0),
        "rf_2xco2": config.get("core_delq2xco2", 3.71),
        "w_initial": config.get("core_initial_upwelling_rate", 3.5),
        "w_variable_fraction": config.get("core_upwelling_variable_part", 0.7),
        "depth_dependent_area": float(config.get("core_ocn_depthdependent", 1)),
        "kappa_dkdt": config.get("core_verticaldiff_top_dkdt", -0.191),
        "land_heat_capacity_enabled": bool(
            config.get("core_landheatcapacity_apply", 1)
        ),
        "land_hc_eff_thickness": config.get("core_landhc_effthickness", 300.0),
        "k_lg": config.get("core_heatxchange_landground", 0.1),
        "k_ns": config.get("core_heatxchange_northsouth", 0.31),
        "feedback_cumt_sensitivity": config.get("core_feedback_cumtsensitivity", 0.08),
        "feedback_q_sensitivity": config.get("core_feedback_qsensitivity", 7.84e-9),
    }

    climate = ClimateUDEBBuilder.from_parameters(params).build()

    time_axis = TimeAxis.from_bounds(
        np.concatenate([erf_years, [erf_years[-1] + 1.0]]).astype(np.float64)
    )

    erf_ts = Timeseries(
        erf_values.astype(np.float64),
        time_axis,
        "W/m^2",
        InterpolationStrategy.Linear,
    )

    schema = VariableSchema()
    schema.add_variable("Effective Radiative Forcing", "W/m^2")
    schema.add_variable("Surface Temperature", "K", GridType.FourBox)
    schema.add_variable("Heat Uptake", "W/m^2")
    schema.add_variable("Ocean Heat Content", "J/m^2")
    schema.add_variable("Sea Surface Temperature", "K")

    model = (
        ModelBuilder()
        .with_time_axis(time_axis)
        .with_schema(schema)
        .with_rust_component(climate)
        .with_exogenous_variable("Effective Radiative Forcing", erf_ts)
        .with_initial_values({"Surface Temperature": 0.0})
        .build()
    )

    return model


def construct_step_forcing(
    years: np.ndarray,
    rf_2xco2: float,
    step_year: float = 1851.0,
) -> np.ndarray:
    """
    Construct ABRUPT-2XCO2 step forcing: 0 before step_year, rf_2xco2 after.

    Parameters
    ----------
    years
        Array of year values
    rf_2xco2
        Radiative forcing for 2xCO2 (W/m^2)
    step_year
        Year at which forcing steps up (default 1851)

    Returns
    -------
    Forcing array matching years
    """
    return np.where(years >= step_year, rf_2xco2, 0.0)


def run_ocean_scenario(  # noqa: PLR0913
    name: str,
    *,
    shock_rtol: float = DEFAULT_RTOL,
    converge_rtol: float = 2e-2,
    final_rtol: float = 2e-2,
    skip: int = 5,
    shock_end: int = 25,
    converge_start: int = 55,
) -> None:
    """
    Run an ocean regression scenario and compare surface temperature.

    Loads reference data, constructs step forcing from the config,
    builds and runs the RSCM model, then compares the global mean
    surface temperature against the MAGICC reference using phased
    tolerances (shock, convergence, final).

    Parameters
    ----------
    name
        Scenario name (e.g., "02_constant_upwelling")
    shock_rtol
        Relative tolerance for the shock and transition phases.
    converge_rtol
        Relative tolerance for the convergence phase.
    final_rtol
        Relative tolerance for the last 20 indices.
    skip
        Initial indices to skip (step forcing onset transient).
    shock_end
        End of shock phase (index).
    converge_start
        Start of convergence phase (index).
    """
    df, config = load_data(name)
    years, expected_temp = get_variable_values(df, "Surface Temperature")

    rf_2xco2 = config.get("core_delq2xco2", 3.71)
    erf = construct_step_forcing(years, rf_2xco2)

    model = build_ocean_model(config, years, erf)
    model.run()

    results = model.timeseries()
    temp_4box = results.get_fourbox_timeseries_by_name("Surface Temperature")
    assert temp_4box is not None, "Surface Temperature not found in results"
    actual_temp = fourbox_global_mean(temp_4box.values())

    assert_allclose_phased(
        actual_temp,
        expected_temp,
        skip=skip,
        shock_end=shock_end,
        converge_start=converge_start,
        shock_rtol=shock_rtol,
        converge_rtol=converge_rtol,
        final_rtol=final_rtol,
        atol=DEFAULT_ATOL,
        name=name,
    )


def test_ocean_01_diffusion_only():
    """
    Test 01: Diffusion only (no upwelling).

    Simplest ocean configuration: vertical diffusion transports heat
    downward, no upwelling circulation. Tests the core tridiagonal
    diffusion solver in isolation.
    """
    run_ocean_scenario("01_diffusion_only", final_rtol=5e-3)


def test_ocean_02_constant_upwelling():
    """
    Test 02: Constant upwelling.

    Adds constant upwelling circulation (w=3.5 m/yr) to diffusion.
    Variable fraction is zero so upwelling rate does not change
    with temperature.
    """
    run_ocean_scenario("02_constant_upwelling", final_rtol=5e-3)


def test_ocean_03_depth_dependent_area():
    """
    Test 03: Depth-dependent ocean area.

    Enables the hypsometric profile so the ocean basin narrows with
    depth, affecting diffusive and advective heat transport.
    """
    run_ocean_scenario("03_depth_dependent_area")


@pytest.mark.xfail(reason="~10% warm bias from variable upwelling treatment (see #108)")
def test_ocean_04_variable_upwelling():
    """
    Test 04: Variable (temperature-dependent) upwelling.

    Upwelling rate decreases as surface temperature anomaly increases,
    simulating AMOC slowdown. 70% of the upwelling is variable.
    """
    run_ocean_scenario("04_variable_upwelling")


def test_ocean_05_temp_dependent_diffusivity():
    """
    Test 05: Temperature-dependent diffusivity.

    Vertical diffusivity decreases as the ocean stratifies (vertical
    temperature gradient increases), parameterised by kappa_dkdt.
    """
    run_ocean_scenario("05_temp_dependent_diffusivity")


def test_ocean_06_ground_heat():
    """
    Test 06: Ground heat reservoir.

    Enables the land heat capacity damping, where a ground reservoir
    absorbs and releases heat from the land surface.

    Uses wider shock tolerance because the ground heat coupling
    amplifies the step forcing onset transient.
    """
    run_ocean_scenario("06_ground_heat", shock_rtol=5e-2, skip=15)


def test_ocean_07_interhemispheric_exchange():
    """
    Test 07: Inter-hemispheric heat exchange.

    Enables North-South heat exchange between ocean boxes,
    parameterised by k_ns.
    """
    run_ocean_scenario("07_interhemispheric_exchange")


@pytest.mark.xfail(reason="Short run dominated by step forcing onset transient")
def test_ocean_08_sst_to_sat():
    """
    Test 08: SST-to-SAT adjustment.

    Short 10-year run validating the ocean-to-atmosphere surface
    temperature adjustment (alpha, gamma parameters). Uses full
    default MAGICC configuration.

    Config:
    - startyear: 1850, endyear: 1860
    - Full default MAGICC7 parameters
    """
    df, config = load_data("08_sst_to_sat")
    years, expected_temp = get_variable_values(df, "Surface Temperature")

    rf_2xco2 = config.get("core_delq2xco2", 3.71)
    erf = construct_step_forcing(years, rf_2xco2)

    # ocean_08 uses full defaults (no explicit overrides for most params)
    params = {
        "ecs": config.get("core_climatesensitivity", 3.0),
        "rf_2xco2": rf_2xco2,
    }
    climate = ClimateUDEBBuilder.from_parameters(params).build()

    time_axis = TimeAxis.from_bounds(
        np.concatenate([years, [years[-1] + 1.0]]).astype(np.float64)
    )
    erf_ts = Timeseries(
        erf.astype(np.float64),
        time_axis,
        "W/m^2",
        InterpolationStrategy.Linear,
    )

    schema = VariableSchema()
    schema.add_variable("Effective Radiative Forcing", "W/m^2")
    schema.add_variable("Surface Temperature", "K", GridType.FourBox)
    schema.add_variable("Heat Uptake", "W/m^2")
    schema.add_variable("Ocean Heat Content", "J/m^2")
    schema.add_variable("Sea Surface Temperature", "K")

    model = (
        ModelBuilder()
        .with_time_axis(time_axis)
        .with_schema(schema)
        .with_rust_component(climate)
        .with_exogenous_variable("Effective Radiative Forcing", erf_ts)
        .with_initial_values({"Surface Temperature": 0.0})
        .build()
    )
    model.run()

    results = model.timeseries()
    temp_4box = results.get_fourbox_timeseries_by_name("Surface Temperature")
    assert temp_4box is not None, "Surface Temperature not found in results"
    actual_temp = fourbox_global_mean(temp_4box.values())

    npt.assert_allclose(
        actual_temp,
        expected_temp,
        rtol=0.1,
        atol=DEFAULT_ATOL,
        err_msg="Surface temperature mismatch for ocean_08_sst_to_sat",
    )


def test_ocean_09_time_varying_ecs():
    """
    Test 09: Time-varying ECS.

    Enables ECS feedback sensitivities so that the effective climate
    sensitivity evolves over time based on cumulative temperature and
    forcing level.
    """
    run_ocean_scenario("09_time_varying_ecs")


@pytest.mark.xfail(reason="Ramp forcing amplifies relative error at small early values")
def test_ocean_10_full_default():
    """
    Test 10: Full default MAGICC7 configuration (1pctCO2 scenario).

    Uses the 1% per year CO2 increase scenario with full default
    MAGICC7 parameters. Unlike the ABRUPT-2XCO2 scenarios, forcing
    ramps up gradually over 150 years.

    The forcing is computed from the 1pctCO2 concentration pathway
    rather than constructed as a step function.

    Config:
    - Full default MAGICC7 parameters
    - file_co2_conc: 1PCTCO2_CO2_CONC.IN
    - startyear: 1850, endyear: 2000
    """
    df, config = load_data("10_full_default")
    years, expected_temp = get_variable_values(df, "Surface Temperature")

    # For 1pctCO2, forcing is not a simple step function.
    # Compute from CO2 concentration: F = rf_2xco2 * ln(C/C0) / ln(2)
    # 1pctCO2 means C(t) = C0 * 1.01^(t - t0) for t > t0
    rf_2xco2 = config.get("core_delq2xco2", 3.71)
    start_year = config.get("startyear", 1850)
    dt = years - start_year
    # First year is equilibrium (no forcing), then 1% per year increase
    co2_ratio = np.where(dt > 0, 1.01**dt, 1.0)
    erf = rf_2xco2 * np.log(co2_ratio) / np.log(2.0)

    # Full defaults: just set ecs and rf_2xco2
    params = {
        "ecs": config.get("core_climatesensitivity", 3.0),
        "rf_2xco2": rf_2xco2,
    }
    climate = ClimateUDEBBuilder.from_parameters(params).build()

    time_axis = TimeAxis.from_bounds(
        np.concatenate([years, [years[-1] + 1.0]]).astype(np.float64)
    )
    erf_ts = Timeseries(
        erf.astype(np.float64),
        time_axis,
        "W/m^2",
        InterpolationStrategy.Linear,
    )

    schema = VariableSchema()
    schema.add_variable("Effective Radiative Forcing", "W/m^2")
    schema.add_variable("Surface Temperature", "K", GridType.FourBox)
    schema.add_variable("Heat Uptake", "W/m^2")
    schema.add_variable("Ocean Heat Content", "J/m^2")
    schema.add_variable("Sea Surface Temperature", "K")

    model = (
        ModelBuilder()
        .with_time_axis(time_axis)
        .with_schema(schema)
        .with_rust_component(climate)
        .with_exogenous_variable("Effective Radiative Forcing", erf_ts)
        .with_initial_values({"Surface Temperature": 0.0})
        .build()
    )
    model.run()

    results = model.timeseries()
    temp_4box = results.get_fourbox_timeseries_by_name("Surface Temperature")
    assert temp_4box is not None, "Surface Temperature not found in results"
    actual_temp = fourbox_global_mean(temp_4box.values())

    npt.assert_allclose(
        actual_temp,
        expected_temp,
        rtol=0.1,
        atol=DEFAULT_ATOL,
        err_msg="Surface temperature mismatch for ocean_10_full_default (1pctCO2)",
    )
