"""
Core classes and functions for Rust Simple Climate Models (RSCMs)
"""

from rscm._lib.core import (
    FourBoxGrid,
    FourBoxRegion,
    FourBoxSlice,
    FourBoxTimeseriesWindow,
    GridType,
    HemisphericGrid,
    HemisphericRegion,
    HemisphericSlice,
    HemisphericTimeseriesWindow,
    InterpolationStrategy,
    Model,
    ModelBuilder,
    PythonComponent,
    RequirementDefinition,
    RequirementType,
    ScalarGrid,
    ScalarRegion,
    TimeAxis,
    Timeseries,
    TimeseriesCollection,
    TimeseriesWindow,
    VariableType,
)

__all__ = [
    "FourBoxGrid",
    "FourBoxRegion",
    "FourBoxSlice",
    "FourBoxTimeseriesWindow",
    "GridType",
    "HemisphericGrid",
    "HemisphericRegion",
    "HemisphericSlice",
    "HemisphericTimeseriesWindow",
    "InterpolationStrategy",
    "Model",
    "ModelBuilder",
    "PythonComponent",
    "RequirementDefinition",
    "RequirementType",
    "ScalarGrid",
    "ScalarRegion",
    "TimeAxis",
    "Timeseries",
    "TimeseriesCollection",
    "TimeseriesWindow",
    "VariableType",
]
