name: Release

on:
  push:
    tags: ['v*']

defaults:
  run:
    shell: bash

jobs:
  draft-release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Install Rust
      - name: Install rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Cache rust
        uses: Swatinem/rust-cache@v2
      # Install UV + Python
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      # Install and build the project
      - name: Add version to environment
        run: |
          uv sync --all-extras --dev
          PROJECT_VERSION=$(python -c 'import rscm; print(rscm.__version__)')
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
      - name: Build a wheel
        # TODO: Do this via cibuildwheel
        run: |
          uv build
      # Create release notes
      - name: Generate Release Notes
        run: |
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty='format:* %h %s' --no-merges >> ".github/release_template.md"
      - name: Create Release Draft
        uses: softprops/action-gh-release@v2
        with:
          body_path: ".github/release_template.md"
          token: "${{ secrets.PAT }}"
          draft: true
          files: |
            dist/rscm-${{ env.PROJECT_VERSION }}-*.whl
            dist/rscm-${{ env.PROJECT_VERSION }}.tar.gz
